Repository 5-ReBook/ReBook_BE, pull requests merged in 2024-08, with the labels that each got.

#8 add template
  .github/ISSUE_TEMPLATE/-task-템플릿.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/refactoring.yml
  .github/ISSUE_TEMPLATE/test.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: enhancement

#10 [fix] change enviroment
  src/main/resources/application.yml
Labels: enhancement

#16 [fix] move securityConfig, JWT dir to global
  src/main/java/com/be/rebook/domain/members/service/MemberService.java
  src/main/java/com/be/rebook/domain/members/service/ReissueService.java
  src/main/java/com/be/rebook/global/security/config/SecurityConfig.java
  src/main/java/com/be/rebook/global/security/jwt/CustomLogoutFilter.java
  src/main/java/com/be/rebook/global/security/jwt/JWTFilter.java
  src/main/java/com/be/rebook/global/security/jwt/JWTUtil.java
  src/main/java/com/be/rebook/global/security/jwt/LoginFilter.java
Labels: enhancement

#18 [fix] Product 패키지명 및 구조 변경
  .gitignore
  myapp.log
  src/main/java/com/be/rebook/domain/product/dto/ProductResponseDTO.java
  src/main/java/com/be/rebook/domain/product/entity/Product.java
  src/main/java/com/be/rebook/domain/product/repository/ProductRepository.java
  src/main/java/com/be/rebook/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/be/rebook/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/be/rebook/domain/product/service/ProductService.java
  src/main/java/com/be/rebook/domain/product/type/ProductStatus.java
  src/main/java/com/be/rebook/domain/productImage/domain/ProductImage.java
Labels: enhancement

#17 15 -feature-Cover returning objects type with Optional at repositories
  .DS_Store
  src/main/java/com/be/rebook/domain/members/repository/MajorsRepository.java
  src/main/java/com/be/rebook/domain/members/repository/MembersRepository.java
  src/main/java/com/be/rebook/domain/members/repository/UniversitiesRepository.java
  src/main/java/com/be/rebook/domain/members/service/CustomUserDetailService.java
  src/main/java/com/be/rebook/domain/members/service/MemberService.java
  src/main/java/com/be/rebook/global/exception/ErrorCode.java
Labels: enhancement

#25 Generate multimodule gradle
  build.gradle
  rebook-auth/build.gradle
  rebook-common/build.gradle
  rebook-common/src/main/java/com/be/rebook/utils/config/BaseEntity.java
  rebook-common/src/main/java/com/be/rebook/utils/config/BaseResponse.java
  rebook-common/src/main/java/com/be/rebook/utils/config/QuerydslConfiguration.java
  rebook-common/src/main/java/com/be/rebook/utils/config/S3Config.java
  rebook-common/src/main/java/com/be/rebook/utils/exception/BaseException.java
  rebook-common/src/main/java/com/be/rebook/utils/exception/ErrorCode.java
  rebook-common/src/main/java/com/be/rebook/utils/exception/ErrorResponse.java
  rebook-common/src/main/java/com/be/rebook/utils/exception/GlobalExceptionHandler.java
  rebook-common/src/resources/application.yml
  rebook-members/build.gradle
  rebook-utils/build.gradle
  settings.gradle
Labels: enhancement

#27 21 refactoring product to module
  rebook-product/build.gradle
  rebook-product/src/main/java/com/be/rebook/product/ProductApplication.java
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductRequestDTO.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductResponseDTO.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Members.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Product.java
  rebook-product/src/main/java/com/be/rebook/product/entity/ProductImage.java
  rebook-product/src/main/java/com/be/rebook/product/repository/MembersRepository.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductImageRepository.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepository.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepositoryCustom.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepositoryImpl.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
  rebook-product/src/main/java/com/be/rebook/product/type/ProductStatus.java
  settings.gradle
Labels: enhancement

#28 26 feature 빌드 다듬기
  build.gradle
  rebook-auth/build.gradle
  rebook-auth/src/main/java/com/be/rebook/auth/SecurityApplication.java
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/JWTFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/JWTUtil.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/CustomUserDetailService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/JoinService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/resources/application.yml
  rebook-common/build.gradle
  rebook-common/src/main/java/com/be/rebook/common/config/BaseEntity.java
  rebook-common/src/main/java/com/be/rebook/common/config/BaseResponse.java
  rebook-common/src/main/java/com/be/rebook/common/config/QuerydslConfiguration.java
  rebook-common/src/main/java/com/be/rebook/common/config/S3Config.java
  rebook-common/src/main/java/com/be/rebook/common/exception/BaseException.java
  rebook-common/src/main/java/com/be/rebook/common/exception/ErrorCode.java
  rebook-common/src/main/java/com/be/rebook/common/exception/ErrorResponse.java
  rebook-common/src/main/java/com/be/rebook/common/exception/GlobalExceptionHandler.java
  rebook-members/build.gradle
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
  rebook-members/src/main/java/com/be/rebook/members/repository/MajorsRepository.java
  rebook-members/src/main/java/com/be/rebook/members/service/MemberService.java
  rebook-members/src/main/resources/application.yml
  rebook-product/build.gradle
  rebook-product/src/main/java/com/be/rebook/product/ProductApplication.java
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Product.java
  rebook-product/src/main/java/com/be/rebook/product/entity/ProductImage.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
  rebook-product/src/main/resources/application.yml
Labels: enhancement

#29 26 feature 개발환경 구축을 위한 도커 컴포즈 환경 구성
  build.gradle
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
  rebook-auth/Dockerfile
  rebook-common/src/main/java/com/be/rebook/common/config/BaseResponse.java
  rebook-members/Dockerfile
  rebook-product/Dockerfile
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
Labels: enhancement

#34 31 Product 관련 내용 수정 및 로직 분리
  build.gradle
  rebook-auth/src/main/java/com/be/rebook/auth/SecurityApplication.java
  rebook-auth/src/main/java/com/be/rebook/auth/config/SecurityConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/CustomUserDetails.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/JoinDTO.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/SignupDTO.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/CustomLogoutFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/JWTFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/JWTUtil.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/LoginFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/type/TokenCategory.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/type/TokenExpiryConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
  rebook-auth/src/main/resources/application.yml
  rebook-common/src/main/java/com/be/rebook/common/argumentresolver/auth/Auth.java
  rebook-common/src/main/java/com/be/rebook/common/argumentresolver/auth/MemberLoginInfo.java
  rebook-common/src/main/java/com/be/rebook/common/config/BaseResponse.java
  rebook-common/src/main/java/com/be/rebook/common/exception/ErrorCode.java
  rebook-common/src/main/java/com/be/rebook/common/exception/ErrorResponse.java
  rebook-common/src/main/java/com/be/rebook/common/exception/GlobalExceptionHandler.java
  rebook-common/src/main/java/com/be/rebook/common/service/S3Service.java
  rebook-product/src/main/java/com/be/rebook/product/ProductApplication.java
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductRequestDTO.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductResponseDTO.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Members.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Product.java
  rebook-product/src/main/java/com/be/rebook/product/repository/MembersRepository.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepository.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
  rebook-product/src/main/resources/application.yml
Labels: enhancement

#33 30 feature auth 모듈 유저 인증 기능 구현
  build.gradle
  docker-compose.yml
  eureka-server/Dockerfile
  eureka-server/build.gradle
  eureka-server/src/main/java/com/be/rebook/eurekaserver/EurekaServerApplication.java
  eureka-server/src/main/resources/application.yml
  rebook-auth/build.gradle
  rebook-auth/src/main/java/com/be/rebook/auth/SecurityApplication.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/JWTUtil.java
  rebook-auth/src/main/resources/application.yml
  rebook-common/build.gradle
  rebook-common/src/main/java/com/be/rebook/common/argumentresolver/auth/AuthArgumentResolver.java
  rebook-common/src/main/java/com/be/rebook/common/argumentresolver/auth/MemberLoginInfo.java
  rebook-common/src/main/java/com/be/rebook/common/config/WebMvcConfig.java
  rebook-common/src/main/java/com/be/rebook/common/eureka/strategy/InstanceSelectionStrategy.java
  rebook-common/src/main/java/com/be/rebook/common/eureka/strategy/impl/RandomStrategy.java
  rebook-common/src/main/java/com/be/rebook/common/eureka/strategy/impl/RoundRobinStrategy.java
  rebook-common/src/main/java/com/be/rebook/common/restclients/AuthServiceRestClient.java
  rebook-common/src/main/java/com/be/rebook/common/restclients/RestClientFactory.java
  rebook-members/build.gradle
  rebook-members/src/main/java/com/be/rebook/members/MembersApplication.java
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
  rebook-members/src/main/resources/application.yml
  rebook-product/build.gradle
  rebook-product/src/main/java/com/be/rebook/product/ProductApplication.java
  rebook-product/src/main/resources/application.yml
  settings.gradle
  src/main/java/com/be/rebook/ReBookApplication.java
  src/main/java/com/be/rebook/global/config/BaseEntity.java
  src/main/java/com/be/rebook/global/config/BaseResponse.java
  src/main/java/com/be/rebook/global/config/QuerydslConfiguration.java
  src/main/java/com/be/rebook/global/config/S3Config.java
  src/main/java/com/be/rebook/global/exception/BaseException.java
  src/main/java/com/be/rebook/global/exception/ErrorCode.java
  src/main/java/com/be/rebook/global/exception/ErrorResponse.java
  src/main/java/com/be/rebook/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/be/rebook/ReBookApplicationTests.java
Labels: enhancement

#35 19 feature add email verify
  rebook-auth/build.gradle
  rebook-auth/src/main/java/com/be/rebook/auth/config/RedisConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/config/SecurityConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/SignupDTO.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/VerifyDTO.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/EmailService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/RedisManager.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/RedisManagerImpl.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
  rebook-auth/src/main/resources/application.yml
  rebook-common/src/main/java/com/be/rebook/common/exception/ErrorCode.java
  rebook-common/src/main/java/com/be/rebook/common/service/S3Service.java
  rebook-common/src/resources/application.yml
  rebook-members/src/main/java/com/be/rebook/members/service/MemberService.java
Labels: enhancement

#47 37 feature kakao oauth 로그인 추가
  rebook-auth/build.gradle
  rebook-auth/src/main/java/com/be/rebook/auth/RootController.java
  rebook-auth/src/main/java/com/be/rebook/auth/config/SecurityConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/CustomUserDetails.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/JWTUtil.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/LoginFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/handler/OAuthAuthenticationSuccessHandler.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/info/OAuthMemberInfo.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/info/OAuthMemberInfoFactory.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/info/ProviderType.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/info/impl/KaKaoOauthMemberInfo.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/service/CustomOAuth2UserService.java
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
  rebook-auth/src/main/resources/application.yml
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
Labels: enhancement

#46 S3 로직 변경 및 Product에서 @Auth 사용하는 방향으로 수정
  nginx/nginx.conf
  rebook-common/src/main/java/com/be/rebook/common/service/S3Service.java
  rebook-common/src/main/java/com/be/rebook/common/type/S3FolderName.java
  rebook-common/src/resources/application.yml
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductRequestDTO.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductResponseDTO.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Product.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepository.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepositoryCustom.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepositoryImpl.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
  rebook-product/src/main/resources/application.yml
Labels: enhancement

#49 48 회원 가입 로직 수정 및 이메일 인증 토큰 정보 추가
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/type/TokenExpiryConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
  rebook-auth/src/main/resources/application.yml
Labels: enhancement

#55 54 도커파일 경량화
  eureka-server/Dockerfile
  nginx/Dockerfile
  rebook-auth/Dockerfile
  rebook-chat/Dockerfile
  rebook-members/Dockerfile
  rebook-product/Dockerfile
Labels: enhancement

#51 37 fix CookieUtil, Auth yml 수정
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
  rebook-auth/src/main/resources/application.yml
Labels: enhancement

#61 fix : Signout 상시 404 에러 해결
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/CustomLogoutFilter.java
Labels: enhancement

#64 patch :쿠키 관련 에러처리와 로직 리팩토링
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
Labels: refactoring

#66 [feature] prometheus 의존성 추가
  build.gradle
Labels: enhancement

#73 71 refactoring members 비즈니스 로직 분리와 타인 정보 조회 엔드포인트 추가
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
  rebook-members/src/main/java/com/be/rebook/members/dto/OtherUserinfoDTO.java
  rebook-members/src/main/java/com/be/rebook/members/entity/Members.java
  rebook-members/src/main/java/com/be/rebook/members/service/MemberService.java
Labels: enhancement

#78 patch : 타인 정보 조회시 memberId값과 username 추가로 조회
  rebook-members/src/main/java/com/be/rebook/members/dto/OtherUserinfoDTO.java
  rebook-members/src/main/java/com/be/rebook/members/service/MemberService.java
Labels: enhancement

#72 67 상품 페이징 처리 및 페이지네이션 dto 생성
  rebook-common/src/main/java/com/be/rebook/common/dto/PaginationRequestDTO.java
  rebook-common/src/main/java/com/be/rebook/common/dto/PaginationResponseDTO.java
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductRequestDTO.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepositoryCustom.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepositoryImpl.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
  rebook-product/src/main/resources/application.yml
Labels: enhancement

#75 [feat] Refresh Token DB 저장 로직 Redis로 변경 #68
  rebook-auth/src/main/java/com/be/rebook/auth/SecurityApplication.java
  rebook-auth/src/main/java/com/be/rebook/auth/config/SecurityConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/TokenDto.java
  rebook-auth/src/main/java/com/be/rebook/auth/entity/RefreshTokens.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/CustomLogoutFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/JWTUtil.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/LoginFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/handler/OAuthAuthenticationSuccessHandler.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/info/OAuthMemberInfoFactory.java
  rebook-auth/src/main/java/com/be/rebook/auth/repository/RefreshTokensRepository.java
  rebook-auth/src/main/java/com/be/rebook/auth/scheduler/RefreshDeleteDailyScheduler.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
  rebook-common/src/main/java/com/be/rebook/common/exception/ErrorCode.java
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
Labels: enhancement

#82 patch : 타인 정보 조회시 /me 와 url 중복 문제를 해결하기 위해 /info/{username} 으로 변경
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
Labels: enhancement

#85 62 feature 채팅 소켓 api 작성
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
  rebook-chat/src/main/java/com/be/rebook/chat/config/RedisConfig.java
  rebook-chat/src/main/java/com/be/rebook/chat/config/WebSockConfig.java
  rebook-chat/src/main/java/com/be/rebook/chat/controller/ChatController.java
  rebook-chat/src/main/java/com/be/rebook/chat/controller/ChatSocketController.java
  rebook-chat/src/main/java/com/be/rebook/chat/dto/ChatMessage.java
  rebook-chat/src/main/java/com/be/rebook/chat/dto/ChatMessageDTO.java
  rebook-chat/src/main/java/com/be/rebook/chat/dto/ChatRoomDto.java
  rebook-chat/src/main/java/com/be/rebook/chat/dto/CreateChatRoomDto.java
  rebook-chat/src/main/java/com/be/rebook/chat/entity/ChatMessage.java
  rebook-chat/src/main/java/com/be/rebook/chat/entity/ChatRoom.java
  rebook-chat/src/main/java/com/be/rebook/chat/repository/ChatMessageRepository.java
  rebook-chat/src/main/java/com/be/rebook/chat/repository/ChatRoomRepository.java
  rebook-chat/src/main/java/com/be/rebook/chat/service/ChatRoomService.java
  rebook-chat/src/main/java/com/be/rebook/chat/service/ChatService.java
  rebook-chat/src/main/java/com/be/rebook/chat/service/ChatSocketService.java
  rebook-chat/src/main/java/com/be/rebook/chat/service/RedisPublisher.java
  rebook-chat/src/main/java/com/be/rebook/chat/service/RedisSubscriber.java
  rebook-chat/src/main/resources/application.yml
  rebook-chat/src/main/resources/static/favicon.ico
  rebook-chat/src/main/resources/static/index.html
  rebook-common/src/main/java/com/be/rebook/common/argumentresolver/auth/AuthArgumentResolver.java
  rebook-common/src/main/java/com/be/rebook/common/argumentresolver/auth/MemberLoginInfo.java
  rebook-common/src/main/java/com/be/rebook/common/config/WebMvcConfig.java
  rebook-common/src/main/java/com/be/rebook/common/exception/ErrorCode.java
  rebook-common/src/main/java/com/be/rebook/common/restclients/RestClientFactory.java
Labels: enhancement

#80 79 상품 수정 엔드포인트 작성
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Product.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductImageRepository.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
Labels: enhancement

#92 91 refactoring 전역 cors 설정
  nginx/nginx.conf
  rebook-common/src/main/java/com/be/rebook/common/config/WebMvcConfig.java
  rebook-common/src/resources/application.yml
Labels: enhancement

#95 [fix] 채팅 버그 수정 #90
  docker-compose.yml
  nginx/nginx.conf
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
  rebook-chat/src/main/java/com/be/rebook/chat/config/WebSockConfig.java
  rebook-chat/src/main/java/com/be/rebook/chat/controller/ChatController.java
  rebook-chat/src/main/java/com/be/rebook/chat/controller/ChatSocketController.java
  rebook-chat/src/main/java/com/be/rebook/chat/dto/ChatMessageDTO.java
  rebook-chat/src/main/java/com/be/rebook/chat/dto/ChatRoomDto.java
  rebook-chat/src/main/java/com/be/rebook/chat/entity/ChatRoom.java
  rebook-chat/src/main/java/com/be/rebook/chat/repository/ChatRoomRepository.java
  rebook-chat/src/main/java/com/be/rebook/chat/service/ChatService.java
  rebook-chat/src/main/java/com/be/rebook/chat/service/ChatSocketService.java
  rebook-common/src/main/java/com/be/rebook/common/config/WebMvcConfig.java
  rebook-common/src/main/java/com/be/rebook/common/exception/GlobalExceptionHandler.java
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
  rebook-members/src/main/resources/application.yml
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
Labels: enhancement

#94 93 상품 수정 이미지 처리 로직 변경
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductRequestDTO.java
  rebook-product/src/main/java/com/be/rebook/product/entity/Product.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
Labels: enhancement, refactoring

#99 [hotfix] 버그 수정 #97
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
  rebook-product/src/main/java/com/be/rebook/product/service/ProductService.java
Labels: bug

#102 98 cors 처리 전부 nginx로 위임
  nginx/nginx.conf
  rebook-auth/src/main/java/com/be/rebook/auth/config/SecurityConfig.java
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/resources/application.yml
  rebook-chat/src/main/java/com/be/rebook/chat/controller/ChatController.java
  rebook-chat/src/main/resources/application.yml
  rebook-common/src/main/java/com/be/rebook/common/config/WebMvcConfig.java
  rebook-common/src/resources/application.yml
  rebook-members/src/main/java/com/be/rebook/members/controller/MembersController.java
  rebook-members/src/main/resources/application.yml
  rebook-product/src/main/java/com/be/rebook/product/controller/ProductController.java
Labels: enhancement, refactoring

#101 hotfix : mailauth 토큰 내용 가져오지 못했던 버그 수정
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
Labels: enhancement

#104 [refactor] server_name 변경
  nginx/nginx.conf
Labels: refactoring

#108 105 fix cookie dont set in browser
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/CustomLogoutFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/LoginFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/handler/OAuthAuthenticationSuccessHandler.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
  rebook-auth/src/main/resources/application.yml
Labels: enhancement

#109 patch : mailauth 쿠키 path 설정
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
Labels: enhancement

#107 [refactor] No Offset 방식으로 수정
  rebook-common/src/main/java/com/be/rebook/common/dto/PaginationRequestDTO.java
  rebook-product/src/main/java/com/be/rebook/product/dto/ProductRequestDTO.java
  rebook-product/src/main/java/com/be/rebook/product/repository/ProductRepositoryImpl.java
Labels: enhancement

#111 105 patch : 이메일 토큰 쿠키에서 헤더로 변경
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
  rebook-auth/src/main/java/com/be/rebook/auth/utility/CookieUtil.java
Labels: enhancement

#113 patch : 응답헤더 Authorization으로 설정
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/LoginFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/handler/OAuthAuthenticationSuccessHandler.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
Labels: enhancement

#115 patch : 요청 받을때도 Authorization으로 설정
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
Labels: enhancement

#117 patch : Authorization 헤더로 통합취소와 쿠키로 mailauth 되돌리기
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/jwt/LoginFilter.java
  rebook-auth/src/main/java/com/be/rebook/auth/oauth/handler/OAuthAuthenticationSuccessHandler.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
Labels: enhancement

#122 121 fix body로 mailauth 처리
  rebook-auth/src/main/java/com/be/rebook/auth/controller/AuthController.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/SignupDTO.java
  rebook-auth/src/main/java/com/be/rebook/auth/dto/UpdatePasswordDTO.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/ReissueService.java
  rebook-auth/src/main/java/com/be/rebook/auth/service/SignupService.java
Labels: enhancement
